const BaseUrl = "http://localhost:5102/";

export const ENDPOINTS = {
    LOGIN: BaseUrl + "auth/login",
    REGISTER: BaseUrl + "auth/register",
    VERIFY_TOKEN: BaseUrl + "verifytoken",
    GET_TOURNAMENTS: BaseUrl + "tournament",
    ENROLL_IN_TOURNAMENT: (fds) => BaseUrl + "tournament/" + fds + "/enroll",
    GET_ALL_MATCHES: BaseUrl + "match/all",
    GET_MATCHES: BaseUrl + "match",
    POST_MATCH: BaseUrl + "match",
    PUT_MATCH: BaseUrl + "match",
    PUT_SCORE: (matchId) => BaseUrl + "match/" + matchId + "/score",
    POST_TOURNAMENT: BaseUrl + "tournament",
    PUT_TOURNAMENT: BaseUrl + "tournament",
    DELETE_TOURNAMENT: (id) => BaseUrl + "tournament/" + id,
    DELETE_MATCH: (id) => BaseUrl + "match/" + id,
    PLAYERS_IN_TOURNAMENT: (id) => BaseUrl + "tournament/" + id + "/players",
    GET_REFEREES: BaseUrl + "user/referees",
    GET_PLAYERS: BaseUrl + "user/players",
    GET_USERS: BaseUrl + "user",
    GET_PERSONAL_INFO: BaseUrl + "user/personal",
    PUT_USER: BaseUrl + "user",
    DELETE_USER: BaseUrl + "user",
    CHANGE_PASSWORD: BaseUrl + "user/changepassword",
    DOWNLOAD_MATCHES: BaseUrl + "match/download",
    GET_PENDING_REQUESTS: BaseUrl + "tournament/pendingrequests",
    APPROVE_REQUEST: BaseUrl + "tournament/approve",
    DENY_REQUEST: BaseUrl + "tournament/deny",
};
